; This file is for the FamiTone2 library and was generated by FamiStudio

; .if FAMISTUDIO_CFG_C_BINDINGS
; .export _music_data_=music_data_
; .endif

music_data_:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Duty 0
	.word @env0, @env1, @env1
	.byte $00
	.byte $70 ; 01 : Duty 1
	.word @env0, @env1, @env1
	.byte $00
	.byte $b0 ; 02 : Duty 2
	.word @env0, @env1, @env1
	.byte $00
	.byte $f0 ; 03 : Duty 3
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@song0ref4:
	.byte $bf
@song0ref5:
	.byte $80, $44
@song0ref7:
	.byte $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52, $80, $5c, $82, $44, $80, $36, $84, $44, $80, $52
	.byte $82, $5c, $80, $44, $84, $36, $00, $f9, $a3
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $11
	.word @song0ref5
	.byte $bd, $df
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $11
	.word @song0ref5
	.byte $9d, $df
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $11
	.word @song0ref5
	.byte $9d, $f9, $85
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $12
	.word @song0ref5
	.byte $83, $9f
	.byte $ff, $10
	.word @song0ref5
@song0ref128:
	.byte $80, $2c, $82, $44, $80, $52, $84, $5c, $80, $44, $82, $36, $80, $44, $84, $52, $80, $5c, $82, $44, $80, $36, $84, $2c
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $44, $80, $52, $84, $5c, $80, $44, $82, $36, $80, $2c, $84, $44
	.byte $80, $52, $82, $5c, $80, $44, $84, $36
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $12
	.word @song0ref7
	.byte $ff, $11
	.word @song0ref5
	.byte $dd, $9f
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $11
	.word @song0ref5
	.byte $dd
	.byte $ff, $13
	.word @song0ref4
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $11
	.word @song0ref5
	.byte $bd
	.byte $ff, $14
	.word @song0ref4
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $11
	.word @song0ref5
	.byte $bd, $df
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $11
	.word @song0ref5
	.byte $9d, $df
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $11
	.word @song0ref5
	.byte $9d, $f9, $85
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $3c, $82, $3c, $84, $3e, $86, $41, $42, $44, $46, $48, $4a, $4c, $50, $52
	.byte $56, $5a, $5e, $62, $68, $6e, $76, $02, $14, $28, $00, $8f
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $0f
	.word @song0ref7
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $0f
	.word @song0ref7
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $0f
	.word @song0ref7
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $0f
	.word @song0ref7
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $0f
	.word @song0ref7
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $0f
	.word @song0ref7
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $0f
	.word @song0ref7
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $80, $44, $82, $52, $80, $5c, $84, $44, $80, $36, $82, $2c, $80, $44, $84, $52
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $1c
	.word @song0ref128
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $15
	.word @song0ref128
	.byte $ff, $12
	.word @song0ref7
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $11
	.word @song0ref5
	.byte $bd, $df
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $11
	.word @song0ref5
	.byte $9d, $df
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $11
	.word @song0ref5
	.byte $9d, $f9, $85
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $83
	.byte $ff, $13
	.word @song0ref5
	.byte $ff, $12
	.word @song0ref5
	.byte $f9, $f9, $ef, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref715:
	.byte $f9, $f9, $f9, $f9, $97
@song0ref720:
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $c1
@song0ref729:
	.byte $80, $58, $82, $58, $84, $58, $86, $58
@song0ref737:
	.byte $a7
@song0ref738:
	.byte $80, $4e, $82, $4e, $84, $4e, $86, $4e, $97, $80, $52, $82, $52, $84, $52, $86, $52, $a7, $80, $4a, $82, $4a, $84, $4a
	.byte $86, $4a, $a7, $80, $52, $82, $52, $84, $52, $86, $52, $97, $00, $f9, $93
	.byte $ff, $14
	.word @song0ref729
	.byte $80, $44, $82, $44, $84, $44, $86, $44, $97, $00, $9d, $ef
	.byte $ff, $1c
	.word @song0ref729
	.byte $ff, $14
	.word @song0ref729
	.byte $80, $44, $82, $44, $84, $44, $86, $44, $97, $00, $f9, $93
	.byte $ff, $1c
	.word @song0ref729
	.byte $ff, $14
	.word @song0ref729
@song0ref816:
	.byte $80, $44, $82, $44, $84, $44, $86, $44, $97, $00, $f9, $93, $80, $58, $82, $58, $84, $58, $86, $58, $87, $9f
	.byte $ff, $17
	.word @song0ref738
	.byte $ff, $14
	.word @song0ref729
	.byte $44, $f9, $85
@song0ref847:
	.byte $46, $83, $49, $4a, $83, $4d, $4e, $51, $53, $54, $56, $58, $5b, $5c, $5e, $60, $64, $66, $6a, $6c, $70, $74, $7a, $00
	.byte $06, $0e, $18, $29, $00, $f9, $f9, $bf, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $af
	.byte $ff, $1c
	.word @song0ref729
	.byte $ff, $0e
	.word @song0ref729
	.byte $97, $8f, $80, $4a, $82, $4a, $84, $4a, $86, $4a, $a7
	.byte $ff, $0c
	.word @song0ref816
	.byte $ff, $16
	.word @song0ref737
	.byte $bd, $cf
	.byte $ff, $14
	.word @song0ref729
	.byte $ff, $0c
	.word @song0ref816
	.byte $ff, $18
	.word @song0ref737
	.byte $ff, $14
	.word @song0ref729
	.byte $80, $44, $82, $44, $84, $44, $86, $44, $97, $00, $9d, $ef
	.byte $ff, $1c
	.word @song0ref729
	.byte $ff, $14
	.word @song0ref729
	.byte $44, $f9, $83, $80, $2c, $82, $2e, $84, $2e, $86, $31, $33, $35, $36, $39, $3a, $3c, $3e, $40, $42, $44, $46, $48, $4a
	.byte $4e, $50, $54
	.byte $ff, $19
	.word @song0ref729
	.byte $df
@song0ref976:
	.byte $51, $4f, $4d, $4b, $48, $46, $45, $42, $41, $3e, $3d, $3a, $38, $37, $34, $32
	.byte $ff, $14
	.word @song0ref729
@song0ref995:
	.byte $80, $44, $82, $44, $84, $44, $86, $44, $f9, $47, $48, $4b, $4d, $4e, $50, $52, $54, $56, $58, $5a, $5c, $60, $62, $66
	.byte $6a, $6e, $74, $7a, $02, $80, $58, $82, $58, $84, $58, $86, $58, $87, $9f
	.byte $ff, $13
	.word @song0ref738
	.byte $f7
	.byte $ff, $10
	.word @song0ref976
	.byte $ff, $14
	.word @song0ref729
	.byte $ff, $1d
	.word @song0ref995
	.byte $ff, $14
	.word @song0ref737
	.byte $f7
	.byte $ff, $10
	.word @song0ref976
	.byte $ff, $14
	.word @song0ref729
	.byte $ff, $1d
	.word @song0ref995
	.byte $ff, $0f
	.word @song0ref737
	.byte $87, $9f, $80, $52, $82, $52, $84, $52, $86, $52, $f7
	.byte $ff, $10
	.word @song0ref976
	.byte $ff, $14
	.word @song0ref729
	.byte $80, $44, $82, $44, $84, $44, $86, $44, $f7, $81
	.byte $ff, $1f
	.word @song0ref847
	.byte $f9, $c5
	.byte $ff, $25
	.word @song0ref720
	.byte $ff, $14
	.word @song0ref729
	.byte $80, $44, $82, $44, $84, $44, $86, $44, $97, $00, $9d, $ef
	.byte $ff, $1c
	.word @song0ref729
	.byte $ff, $14
	.word @song0ref729
	.byte $ff, $0c
	.word @song0ref816
	.byte $ff, $17
	.word @song0ref737
	.byte $f9, $f9, $f9, $95, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref1134:
	.byte $2c, $9d, $00, $bd
@song0ref1138:
	.byte $3a, $9d, $00
@song0ref1141:
	.byte $bd
@song0ref1142:
	.byte $32, $9d, $00
@song0ref1145:
	.byte $bd, $28, $9d, $2a, $9d, $2c, $9d, $00, $bd, $3a, $9d, $00, $9d, $9f
	.byte $ff, $0f
	.word @song0ref1142
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
@song0ref1177:
	.byte $bd, $32, $9d, $00, $bd, $28
@song0ref1183:
	.byte $9d, $22, $9d, $24, $9d, $00, $bd, $32, $9d, $00, $bd, $2c, $9d, $00, $9d, $9f, $1e
	.byte $ff, $0e
	.word @song0ref1183
	.byte $bd, $28, $9d, $2a, $9d, $2c, $9d, $00, $9d, $9f
	.byte $ff, $13
	.word @song0ref1138
@song0ref1216:
	.byte $bd, $32, $9d, $00, $bd, $28, $8d, $00, $8d, $2a, $8d, $00, $8d
	.byte $ff, $17
	.word @song0ref1134
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $12
	.word @song0ref1141
	.byte $ff, $0f
	.word @song0ref1142
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $14
	.word @song0ref1177
	.byte $bd, $1e
	.byte $ff, $0e
	.word @song0ref1183
	.byte $ff, $0c
	.word @song0ref1145
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $0d
	.word @song0ref1216
	.byte $2c, $dd, $3a, $cf, $38, $8b, $32, $bd, $93, $30, $89
@song0ref1278:
	.byte $28, $9d, $2a, $9d, $2c, $dd
@song0ref1284:
	.byte $3a, $cf, $38, $8b, $32, $d1, $30, $89, $28, $9d, $2a, $9d, $2c, $bd, $9f
	.byte $ff, $0d
	.word @song0ref1284
	.byte $dd, $3a, $cf, $38, $8b, $32, $9d, $b3, $30, $89, $28, $9d, $22, $9d, $24, $dd, $32, $d1, $30, $89, $2c, $d3, $2a, $87
	.byte $1e, $9d, $22, $9d, $24, $9d, $bf, $32, $d1, $30, $89, $2c, $d3, $2a, $87
	.byte $ff, $13
	.word @song0ref1278
	.byte $dd, $3a, $cf, $38, $8b, $32, $d1, $30, $89, $28, $8d, $00, $8d, $2a, $8d, $00, $8d
	.byte $ff, $19
	.word @song0ref1134
	.byte $ff, $0f
	.word @song0ref1142
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $10
	.word @song0ref1141
	.byte $ff, $17
	.word @song0ref1177
	.byte $f9, $f9, $f9, $ef, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref1394:
	.byte $42, $40, $42, $85, $00, $b1
@song0ref1400:
	.byte $52, $83, $00, $97, $4a, $87, $00, $93, $52, $83, $00, $97, $42, $40, $42, $85, $00, $91, $42, $40, $42, $85, $00, $b1
	.byte $52, $83, $00, $97, $42, $40, $42, $85, $00, $91, $4a, $87, $00, $93
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $1d
	.word @song0ref1394
	.byte $91, $9f, $52, $83, $00, $97
@song0ref1477:
	.byte $4a, $87, $00, $93, $42, $40, $42, $85, $01, $52, $83, $00, $87
	.byte $ff, $2c
	.word @song0ref1394
	.byte $42, $40, $42, $85, $00, $91, $9f
	.byte $ff, $26
	.word @song0ref1400
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $22
	.word @song0ref1394
	.byte $ff, $0d
	.word @song0ref1477
@song0ref1536:
	.byte $42, $40, $42, $85, $01, $42, $40, $42, $85, $01
@song0ref1546:
	.byte $42, $40, $42, $85, $01, $42, $40, $42, $85, $01
@song0ref1556:
	.byte $52, $83, $00, $87, $52, $83, $00, $87, $4a, $87, $00, $83, $4a, $87, $00, $83, $52, $83, $00, $87, $52, $83, $00, $87
	.byte $ff, $14
	.word @song0ref1536
@song0ref1583:
	.byte $42, $40, $42, $85, $01, $42, $40, $42, $85, $00, $81, $52, $83, $00, $87, $52, $83, $00, $87
@song0ref1602:
	.byte $42, $40, $42, $85, $01, $42, $40, $42, $85, $01, $4a, $87, $00, $83, $4a, $87, $00, $83
	.byte $ff, $2c
	.word @song0ref1536
	.byte $ff, $14
	.word @song0ref1536
	.byte $ff, $12
	.word @song0ref1546
	.byte $ff, $12
	.word @song0ref1602
	.byte $ff, $13
	.word @song0ref1536
	.byte $00, $81
	.byte $ff, $18
	.word @song0ref1556
	.byte $ff, $14
	.word @song0ref1536
	.byte $ff, $12
	.word @song0ref1546
	.byte $ff, $12
	.word @song0ref1602
	.byte $ff, $2c
	.word @song0ref1536
	.byte $ff, $13
	.word @song0ref1536
	.byte $00, $81
	.byte $ff, $12
	.word @song0ref1546
	.byte $ff, $12
	.word @song0ref1602
	.byte $ff, $2c
	.word @song0ref1536
	.byte $ff, $14
	.word @song0ref1536
	.byte $ff, $12
	.word @song0ref1546
	.byte $ff, $12
	.word @song0ref1602
	.byte $ff, $0b
	.word @song0ref1583
	.byte $ff, $22
	.word @song0ref1546
	.byte $ff, $14
	.word @song0ref1536
	.byte $ff, $12
	.word @song0ref1546
	.byte $ff, $12
	.word @song0ref1602
	.byte $ff, $2c
	.word @song0ref1536
	.byte $ff, $0b
	.word @song0ref1583
	.byte $ff, $1c
	.word @song0ref1536
	.byte $ff, $12
	.word @song0ref1602
	.byte $ff, $2c
	.word @song0ref1536
	.byte $ff, $14
	.word @song0ref1536
	.byte $ff, $1a
	.word @song0ref1546
	.byte $42, $40, $42, $85, $01, $4a, $87, $00, $83
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $2c
	.word @song0ref1394
	.byte $ff, $27
	.word @song0ref1394
	.byte $f9, $f9, $f9, $e3, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97
	.byte $ff, $0d
	.word @song0ref715
	.byte $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch4loop
